### ISSUE TITLE
Test class fails to initialize

### ISSUE THREAD

**Issue by kkrull** [kkrull/javaspec#4]
```
info.javaspec.spec.ClassFactory$UnsupportedConstructor: Unable to find a no-argument constructor for class com.wikitab.difftab.tablature.score.UploadTablatureHttpCommandTest
	at info.javaspec.spec.ClassFactory$UnsupportedConstructor.forClass(ClassFactory.java:40)
	at info.javaspec.spec.ClassFactory.makeInstance(ClassFactory.java:15)
	at info.javaspec.spec.SpecExecutionContext.makeInstance(SpecExecutionContext.java:44)
	at info.javaspec.spec.SpecExecutionContext.makeAndRememberInstance(SpecExecutionContext.java:36)
	at info.javaspec.spec.SpecExecutionContext.makeInstance(SpecExecutionContext.java:46)
	at info.javaspec.spec.SpecExecutionContext.makeAndRememberInstance(SpecExecutionContext.java:36)
	at info.javaspec.spec.SpecExecutionContext.makeInstance(SpecExecutionContext.java:46)
	at info.javaspec.spec.SpecExecutionContext.makeAndRememberInstance(SpecExecutionContext.java:36)
	at info.javaspec.spec.SpecExecutionContext.forDeclaringClass(SpecExecutionContext.java:18)
	at info.javaspec.spec.FieldSpec$DeclaredState.instantiate(FieldSpec.java:58)
	at info.javaspec.spec.FieldSpec.run(FieldSpec.java:36)
	at info.javaspec.context.ClassContext.lambda$run$4(ClassContext.java:57)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at info.javaspec.context.ClassContext.run(ClassContext.java:57)
	at info.javaspec.context.ClassContext.lambda$run$5(ClassContext.java:58)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at info.javaspec.context.ClassContext.run(ClassContext.java:58)
	at info.javaspec.context.ClassContext.lambda$run$5(ClassContext.java:58)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at info.javaspec.context.ClassContext.run(ClassContext.java:58)
	at info.javaspec.runner.JavaSpecRunner.run(JavaSpecRunner.java:60)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at info.javaspec.spec.OuterClassFactory.makeInstance(OuterClassFactory.java:13)
	at info.javaspec.spec.ClassFactory.makeInstance(ClassFactory.java:11)
	... 39 more
Caused by: java.lang.NullPointerException
	at <test class>.<init>
	... 45 more
```

The test class in question passes when it has this:

```
  private TempDirFixture tempDir;
  Establish that = () -> tempDir = TempDirFixture.forClass(getClass());
  Cleanup delete_temp_dir = () -> tempDir.delete();
```

and it fails like this:

```
  private TempDirFixture tempDir;
  Establish that = () -> tempDir = TempDirFixture.forClass(getClass());
  Cleanup delete_temp_dir = tempDir::delete;
```

**Comment by kkrull** [comment]
The null reference was indeed `tempDir`, because setting it some temporary value avoided the issue.

The issue to fix in Javaspec is in a failing field or constructor.  It needs to report this as a test failure instead of letting the exception bubble up to the top.
